quarkus.log.category."org.acme".level=DEBUG

quarkus.http.port=8280

quarkus.swagger-ui.always-include=true

mp.messaging.outgoing.response_events.connector=smallrye-kafka
mp.messaging.outgoing.response_events.topic=query_response_events
mp.messaging.outgoing.response_events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
