quarkus.http.port=8080

kogito.service.url=http://localhost:${quarkus.http.port}

quarkus.kogito.devservices.enabled=false
quarkus.devservices.enabled=false

quarkus.swagger-ui.always-include=true
quarkus.kogito.data-index.graphql.ui.always-include=true

# Kogito runtime persistence configurations
kogito.persistence.type=jdbc
kogito.persistence.proto.marshaller=false
kogito.persistence.query.timeout.millis=10000
quarkus.datasource.db-kind=postgresql
quarkus.flyway.migrate-at-start=true

# Configuration for the incoming cloud events received by the serverless workflows.
#mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
#mp.messaging.incoming.kogito_incoming_stream.path=/
#mp.messaging.incoming.kogito_incoming_stream.method=POST

# Configuration for the helper class EventsProducerResource that send events to the waiting serverless workflows.
mp.messaging.outgoing.response_events.connector=quarkus-http
mp.messaging.outgoing.response_events.url=${K_SINK:${kogito.service.url}}
mp.messaging.outgoing.response_events.method=POST



# INCOMING CONNECTOR

# To set my own default channel configuration, I need to do this:
#kogito.addon.messaging.incoming.defaultName=my_default_kogito_in
#mp.messaging.incoming.my_default_kogito_in.connector=quarkus-http
#mp.messaging.incoming.my_default_kogito_in.path=/my-default-in
#mp.messaging.incoming.my_default_kogito_in.method=POST

# To really have the default kogito_incoming_stream working, we still need to add configurations:
#mp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
#mp.messaging.incoming.kogito_incoming_stream.path=/kogito-default-in
#mp.messaging.incoming.kogito_incoming_stream.method=POST


# works
# mvn quarkus:dev  -Dmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http  -Dmp.messaging.incoming.kogito_incoming_stream.path=/kogito-default-in -Dmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http


# works, but you must then start passing the properties in the command line.
# mvn clean install -Pdefault-connectors -Dmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http  -Dmp.messaging.incoming.kogito_incoming_stream.path=/kogito-default-in -Dmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http
# like this
# java -Dmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http  -Dmp.messaging.incoming.kogito_incoming_stream.path=/kogito-default-in -Dmp.messaging.incoming.kogito_incoming_stream.connector=quarkus-http -jar target/quarkus-app/quarkus-run.jar


# export MP_MESSAGING_INCOMING_KOGITO_INCOMING_STREAM_CONNECTOR=quarkus-http
# export MP_MESSAGING_INCOMING_KOGITO_INCOMING_STREAM_PATH=/kogito-default-in
# export MP_MESSAGING_INCOMING_KOGITO_INCOMING_STREAM_METHOD=POST

# and mvn clean install -Pdefault-connectors   obviously doesn't work

# OUTGOING CONNECTOR

# mp.messaging.outgoing.kogito_outgoing_stream

# in real knative, by default points to the K_SINK env var

# in dev mode, or standalone cases where K_SINK variable is not set

# by default, if we set nothing, event are sent to   http://localhost:9090

# if we start with the changed property it works fine.
# java -Dmp.messaging.outgoing.kogito_outgoing_stream.url=http://localhost:9191  -jar target/quarkus-app/quarkus-run.jar

# if we start with the env variable it works fine.
# export MP_MESSAGING_OUTGOING_KOGITO_OUTGOING_STREAM_URL=http://localhost:9292
# java -jar target/quarkus-app/quarkus-run.jar



#mp.messaging.outgoing.kogito_outgoing_stream.connector=quarkus-http
#mp.messaging.outgoing.kogito_outgoing_stream.url=http://localhost:9191
#mp.messaging.outgoing.kogito_outgoing_stream.method=POST


# Profile to pack this example into a container, to use it execute activate the maven container profile, -Dcontainer
%container.quarkus.container-image.build=true
%container.quarkus.container-image.push=false
%container.quarkus.container-image.group=${USER}
%container.quarkus.container-image.registry=dev.local
%quarkus.container-image.name=timeouts-showcase-embedded
%container.quarkus.container-image.tag=1.0-SNAPSHOT
%container.quarkus.jib.jvm-entrypoint=/home/kogito/kogito-app-launch.sh
%container.quarkus.jib.base-jvm-image=quay.io/kiegroup/kogito-runtime-jvm:latest
%container.quarkus.jib.working-directory=/home/kogito/bin
