quarkus.log.category."org.acme".level=DEBUG

kogito.sw.functions.sendQuery.host=localhost
kogito.sw.functions.sendQuery.port=8283

quarkus.swagger-ui.always-include=true

kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.query_response_events.connector=smallrye-kafka
mp.messaging.incoming.query_response_events.topic=query_response_events
mp.messaging.incoming.query_response_events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

# If the persistence profile wasn't enabled, by default use the H2 in-memory database for the knowledge database (represented by the PanacheQueryRepository).
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:qas-service

quarkus.hibernate-orm.database.generation=update

# persistence profile configurations

# Kogito persistence configurations for enabling the serverless workflow persistence, and for the PanacheQueryRepository.
%persistence.quarkus.datasource.db-kind=postgresql
%persistence.kogito.persistence.type=jdbc
%persistence.kogito.persistence.auto.ddl=true
%persistence.kogito.persistence.query.timeout.millis=10000

# DB configuration
%persistence.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
%persistence.quarkus.datasource.username=postgres
%persistence.quarkus.datasource.password=pass