quarkus.log.category."org.acme".level=DEBUG

quarkus.http.port=8283

quarkus.swagger-ui.always-include=true

# kafka configuration for sending the events to the query-answer-service
mp.messaging.outgoing.response_events.connector=smallrye-kafka
mp.messaging.outgoing.response_events.topic=query_response_events
mp.messaging.outgoing.response_events.value.serializer=org.apache.kafka.common.serialization.StringSerializer

# If the persistence profile wasn't enabled, by default use the H2 in-memory database for the pending queries database (represented by the PanacheQueryRequestRepository).
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:query-service

quarkus.hibernate-orm.database.generation=update

# Build the application with the persistence profile to use a PostgreSQL database for the PanacheQueryRequestRepository.
%persistence.quarkus.datasource.db-kind=postgresql
%persistence.quarkus.datasource.username=postgres
%persistence.quarkus.datasource.password=pass
%persistence.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres