#!/bin/bash

CALLBACK_STATE_TIMEOUTS_WF=switchstatetimeouts
EVENT_STATE_TIMEOUTS_WF=eventstatetimeouts
SWITCH_STATE_TIMEOUTS_WF=eventstatetimeouts

CALLBACK_STATE_TIMEOUTS_URL=`minikube service $CALLBACK_STATE_TIMEOUTS_WF -n timeouts-showcase  --url`
EVENT_STATE_TIMEOUTS_URL=`minikube service $EVENT_STATE_TIMEOUTS_WF -n timeouts-showcase  --url`
SWITCH_STATE_TIMEOUTS_URL=`minikube service $SWITCH_STATE_TIMEOUTS_WF -n timeouts-showcase  --url`

CALLBACK_STATE_TIMEOUTS_URL="$CALLBACK_STATE_TIMEOUTS_URL/$CALLBACK_STATE_TIMEOUTS_WF"
EVENT_STATE_TIMEOUTS_URL="$EVENT_STATE_TIMEOUTS_URL/$EVENT_STATE_TIMEOUTS_WF"
SWITCH_STATE_TIMEOUTS_URL="$SWITCH_STATE_TIMEOUTS_URL/$SWITCH_STATE_TIMEOUTS_WF"


echo "Setting workflows env variables to:"
echo "CALLBACK_STATE_TIMEOUTS_URL=$CALLBACK_STATE_TIMEOUTS_URL"
echo "EVENT_STATE_TIMEOUTS_URL=$EVENT_STATE_TIMEOUTS_URL"
echo "SWITCH_STATE_TIMEOUTS_URL=$SWITCH_STATE_TIMEOUTS_URL"
