quarkus.log.category."org.acme".level=DEBUG

kogito.sw.functions.sendQuery.host=localhost
kogito.sw.functions.sendQuery.port=8280

quarkus.swagger-ui.always-include=true

kafka.bootstrap.servers=localhost:9092

mp.messaging.incoming.query_response_events.connector=smallrye-kafka
mp.messaging.incoming.query_response_events.topic=query_response_events
mp.messaging.incoming.query_response_events.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

%postgresql.kogito.persistence.type=postgresql
%postgresql.kogito.persistence.auto.ddl=true
%postgresql.kogito.persistence.query.timeout.millis=10000

%postgresql.quarkus.datasource.reactive.url=postgresql://localhost:5432/qas-service
%postgresql.quarkus.datasource.username=jbpm
%postgresql.quarkus.datasource.password=jbpm